### ISSUE TITLE
Clickable nodes not styled

### ISSUE THREAD

**Issue by ChappIO** [konsumer/gatsby-remark-graph#6]
I am working with this plugin on a new project, and my diagram is getting pretty complex. I wanted to break it up into multiple diagrams and use the `click nodeId url` syntax to link between them. However, it seems that the `clickable` class is not added to my node. This means my cursor does not become 'pointer'.

Example diagram:

```mermaid
graph LR

one --> two
click two "https://two.com"
```

In the mermaid live editor:
![image](https://user-images.githubusercontent.com/13708940/53298067-548ec200-3828-11e9-8981-fed581b3df2c.png)

In gatsby:
![image](https://user-images.githubusercontent.com/13708940/53298073-6cfedc80-3828-11e9-93f2-45a0d64abd28.png)

**Comment by ChappIO** [comment]
I have been playing around to try and get this fixed. In the process I noticed that you are using client-side rendering. 

I have spent today adding server-side rendering for mermaid. Would you be interested in receiving a PR for this or should I be better off creating a new plugin?

**Comment by ChappIO** [comment]
I created the plugin: https://github.com/ChappIO/gatsby-remark-mermaid
Let me know if you'd like to adopt something like this or if I should continue myself.

**Comment by ChappIO** [comment]
The original problem was the version of mermaid btw. I upgraded to 8.0.0 and then it worked fine.

**Comment by konsumer** [comment]
Sorry, for some reason I missed all this. I just published a version (from #9) that uses mermaid 8: gatsby-remark-graph@0.2.5

Closing for now, but let me know if there are more issues.
